name: FFmpeg Build and Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install required system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Build FFmpeg binaries
        run: node build.js

      - name: List ffmpeg-binaries content
        run: |
          ls -R ffmpeg-binaries
          echo "Total directories:"
          find ffmpeg-binaries -type d | wc -l

      - name: Create ZIP files for each platform
        run: |
          cd ffmpeg-binaries
          for dir in */; do
            platform=${dir%/}
            platform_name="${platform}"
            
            # Check if the directory exists and contains ffmpeg binaries
            if [ -d "$platform" ]; then
              cd "$platform"
              
              # For Windows binaries, look for ffmpeg.exe
              if [[ "$platform" == *"win32"* ]]; then
                if [ -f "ffmpeg.exe" ]; then
                  zip -j "../ffmpeg-${platform_name}.zip" ffmpeg.exe
                  echo "Created zip for $platform_name with ffmpeg.exe"
                else
                  echo "Warning: ffmpeg.exe not found in $platform"
                fi
              # For other platforms, look for ffmpeg
              else
                if [ -f "ffmpeg" ]; then
                  zip -j "../ffmpeg-${platform_name}.zip" ffmpeg
                  echo "Created zip for $platform_name with ffmpeg"
                else
                  echo "Warning: ffmpeg not found in $platform"
                fi
              fi
              
              cd ..
            else
              echo "Warning: Directory $platform does not exist"
            fi
          done
          cd ..

      - name: Upload FFmpeg binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-binaries-zips
          path: ffmpeg-binaries/ffmpeg-*.zip

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ffmpeg-binaries-zips
          path: ffmpeg-binaries-zips

      - name: List downloaded artifacts
        run: |
          ls -R ffmpeg-binaries-zips
          echo "Total ZIP files:"
          find ffmpeg-binaries-zips -type f -name "ffmpeg-*.zip" | wc -l

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.current-version}}
          name: Release v${{ steps.package-version.outputs.current-version}}
          draft: false
          prerelease: false
          files: ffmpeg-binaries-zips/ffmpeg-*.zip
